import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Provider } from "@/components/chakra/provider";
import IncompatibleScreenWrapper from "@/lib/react-utils/IncompatibleScreenWrapper";
import "./globals.css";
import SplashScreen from "@/lib/react-utils/LoadingSession";
import QueryClientProvider from "@/lib/tanstack-query/QueryClientProvider";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const inter = Inter({
	variable: "--font-inter",
	subsets: ["latin"],
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning className={`${inter.className}`}>
			<body>
				<ClerkProvider>
					<QueryClientProvider>
						<Provider>
							<IncompatibleScreenWrapper>
								<SplashScreen>{children}</SplashScreen>
							</IncompatibleScreenWrapper>
						</Provider>
					</QueryClientProvider>
				</ClerkProvider>
			</body>
		</html>
	);
}
